title    Tinfoil Hat Linux II (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-hardened
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-hardened.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID%
