title    Tinfoil Hat Linux II (speech) (%ARCH%, UEFI) with speech
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-hardened
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-hardened.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% accessibility=on
